### ISSUE TITLE
grails-4 / boot devtools incompatibility

### ISSUE THREAD

**Issue by zyro23** [gpc/greenmail#31]
likely already fixed, needs release. see https://github.com/gpc/greenmail/pull/30#issuecomment-501348040

**Comment by virtualdogbert** [comment]
Any idea when a new release may come?

**Comment by matthijsbierman** [comment]
@sbglasius are there plans to release a new version of the plugin, or should it be considered abandoned?

**Comment by sbglasius** [comment]
better late than never: New release is here.. 

Apparently requirement-driven-development on my part
