### ISSUE TITLE
Gradle 7 support

### ISSUE THREAD

**Issue by verglor** [gpc/greenmail#33]
Since [Gradle 7 no longer supports deprecated `compile` scope](https://docs.gradle.org/current/userguide/upgrading_version_6.html#sec:configuration_removal) it should be replaced by `implementation` / `api` scope in [build.gradle](https://github.com/gpc/greenmail/blob/486216eeedb5042ef2dd2dd7f67b6c7bec91532b/build.gradle#L43-L57). Otherwise dependency on `com.icegreen:greenmail:1.5.3` is missing in grails app.

**Workaround**
Add dependency in grails app:
```
    implementation 'com.icegreen:greenmail:1.5.3'
```

**Comment by bkoehm** [comment]
PR #35 may be of interest to you.

**Comment by sbglasius** [comment]
Fixed with the latest release
