### ISSUE TITLE
greenMail#stop() fails; should call super

### ISSUE THREAD

**Issue by ldeck** [gpc/greenmail#5]
grails.plugin.greenmail.GreenMail is not in the same package as com.icegreen.greenmail.util.GreenMail.. thus stop() fails to find the super's services field at runtime as (being a Java class) it has package protection on the field.

It should call super akin to the start() method.

**Comment by MiguelAngel82** [comment]
Hi all.

I have a problem when the method stop() is called from an integration test in a Grails 3.1.4 application. The error said: "No such property services".

Anyone has the same problem? Is related to this?

Thank you!
